### ISSUE TITLE
Can't add a New Extension to Existing Draft Process

### ISSUE THREAD

**Issue by alexanderkiel** [highmed/highmed-dsf#165]
I have an existing BPE process represented by it's ActivityDefinition. The status of the ActivityDefinition is `draft`. I would expect that I can add more Extensions, CodeSystems etc. 

However, if I start the BPE with my new JAR, containing the new Extension, the BPE tries to update the extension instead of creating it in the FHIR server. Because the Extension has no ID in this state, I get an NPE at: 

```
java.lang.NullPointerException: null
  at org.highmed.dsf.bpe.service.FhirResourceHandlerImpl.update(FhirResourceHandlerImpl.java:399) ~[dsf-bpe-server-0.4.0-SNAPSHOT.jar:0.4.0-SNAPSHOT]
  at org.highmed.dsf.bpe.service.FhirResourceHandlerImpl.updateToDraft(FhirResourceHandlerImpl.java:387) ~[dsf-bpe-server-0.4.0-SNAPSHOT.jar:0.4.0-SNAPSHOT]
  at org.highmed.dsf.bpe.service.FhirResourceHandlerImpl.fromDraft(FhirResourceHandlerImpl.java:304) ~[dsf-bpe-server-0.4.0-SNAPSHOT.jar:0.4.0-SNAPSHOT]
  at org.highmed.dsf.bpe.service.FhirResourceHandlerImpl.toEntry(FhirResourceHandlerImpl.java:254) ~[dsf-bpe-server-0.4.0-SNAPSHOT.jar:0.4.0-SNAPSHOT]
```

What I was able to find is that the draft state is set from the ProcessStateChangeOutcome of the ActivityDefinition in FhirResourceHandlerImpl line 98. 

I was able to add the Extension by incrementing the version number of the plugin and all my processes. I'm not sure if this is expected behavior for draft processes. Certainly it should not end in an NPE.

**Comment by hhund** [comment]
You're describing a use case that I had not tested yet. Adding FHIR resources to an existing draft process that was already created and set active with FHIR resources. So far I only tested updating existing draft resources. For ease of development your use case should be supported.

In addition to incrementing the version number, a workaround would be of course to stop both servers, clean both the FHIR and BPE server's databases and then start both servers again.
