### ISSUE TITLE
NullPointerException at Fhir Jetty Server startup

### ISSUE THREAD

**Issue by FloSeidel** [highmed/highmed-dsf#2]
While I got the docker variant running, the native run seems to make problems on my system ("Manual Integration Testing (without Docker)").  When starting the Fhir Server with the command mentioned below the following output will show up (I already run the before mentioned steps (mvn install + postresql setup)). 

I'm running a Windows 10 machine and tried the following java jdk versions:

openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)

openjdk version "11.0.3-ojdkbuild" 2019-04-16 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.3-ojdkbuild+7-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.3-ojdkbuild+7-LTS, mixed mode)

Location:
    C:\projects\highmed-dsf\dsf-fhir\dsf-fhir-server-jetty
Command:
    mvn exec:java -D"exec.mainClass"="org.highmed.dsf.fhir.FhirJettyServerHttps"

Output:
```
[INFO] Scanning for projects...
[INFO]
[INFO] ---------------< org.highmed.dsf:dsf-fhir-server-jetty >----------------
[INFO] Building dsf-fhir-server-jetty 0.1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]    
[INFO] --- exec-maven-plugin:1.6.0:java (default-cli) @ dsf-fhir-server-jetty ---
INFO    org.highmed.dsf.fhir.FhirJettyServerHttps.main() - DbMigrator.migrate(105) | Executing DB migration ...
INFO    org.highmed.dsf.fhir.FhirJettyServerHttps.main() - DbMigrator.migrate(107) | Executing DB migration [Done]    
INFO    org.highmed.dsf.fhir.FhirJettyServerHttps.main() - Log.initialized(193) | Logging initialized @13847ms to org.eclipse.jetty.util.log.Slf4jLog
INFO    org.highmed.dsf.fhir.FhirJettyServerHttps.main() - CertificateCheckerImpl.lambda$checkCertificateAndScheduleWarning$0(72) | Using CA certificate 'CN=Test, C=DE'. Valid from '2019-06-21T11:07:22+0200' to '2029-06-18T11:07:22+0200' to check certificate trust
INFO    org.highmed.dsf.fhir.FhirJettyServerHttps.main() - CertificateCheckerImpl.checkCertificateAndScheduleWarning(82) | Certificate 'CN=localhost, C=DE' trusted. Valid from '2019-06-21T11:07:32+0200' to '2021-06-20T11:07:32+0200'.
INFO    org.highmed.dsf.fhir.FhirJettyServerHttps.main() - JettyServer.<init>(299) | Web inf classes: dirs []
INFO    org.highmed.dsf.fhir.FhirJettyServerHttps.main() - JettyServer.<init>(300) | Web inf classes: jars []
INFO    org.highmed.dsf.fhir.FhirJettyServerHttps.main() - JettyServer.<init>(304) | Adding filter: org.highmed.dsf.fhir.authentication.AuthenticationFilter    
INFO    org.highmed.dsf.fhir.FhirJettyServerHttps.main() - Server.doStart(370) | jetty-9.4.18.v20190429; built: 2019-04-29T20:42:08.989Z; git: e1bc35120a6617ee3df052294e433f3a25ce7097; jvm 11+28
INFO    org.highmed.dsf.fhir.FhirJettyServerHttps.main() - AnnotationConfiguration.scanForAnnotations(481) | Scanning elapsed time=0ms
INFO    org.highmed.dsf.fhir.FhirJettyServerHttps.main() - ContextHandler$Context.log(2349) | No Spring WebApplicationInitializer types detected on classpath
INFO    org.highmed.dsf.fhir.FhirJettyServerHttps.main() - DefaultSessionIdManager.doStart(365) | DefaultSessionIdManager workerName=node0
INFO    org.highmed.dsf.fhir.FhirJettyServerHttps.main() - DefaultSessionIdManager.doStart(370) | No SessionScavenger set, using defaults
INFO    org.highmed.dsf.fhir.FhirJettyServerHttps.main() - HouseKeeper.startScavenging(149) | node0 Scavenging every 600000ms
DEBUG   org.highmed.dsf.fhir.FhirJettyServerHttps.main() - AuthenticationFilter.init(34) | Init org.highmed.dsf.fhir.authentication.AuthenticationFilter
WARN    org.highmed.dsf.fhir.FhirJettyServerHttps.main() - WebAppContext.doStart(554) | Failed startup of context o.e.j.w.WebAppContext@45686e58{/fhir,null,UNAVAILABLE}    
java.lang.NullPointerException: null
        at org.highmed.dsf.fhir.authentication.AuthenticationFilter.init(AuthenticationFilter.java:37) ~[dsf-fhir-server-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
        at org.eclipse.jetty.servlet.FilterHolder.initialize(FilterHolder.java:136) ~[jetty-servlet-9.4.18.v20190429.jar:9.4.18.v20190429]
        at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$0(ServletHandler.java:750) ~[jetty-servlet-9.4.18.v20190429.jar:9.4.18.v20190429]
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:?]
        at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734) ~[?:?]
        at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[?:?]
        at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:744) ~[jetty-servlet-9.4.18.v20190429.jar:9.4.18.v20190429]
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:369) ~[jetty-servlet-9.4.18.v20190429.jar:9.4.18.v20190429]
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1497) ~[jetty-webapp-9.4.18.v20190429.jar:9.4.18.v20190429]
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1459) ~[jetty-webapp-9.4.18.v20190429.jar:9.4.18.v20190429]
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:852) ~[jetty-server-9.4.18.v20190429.jar:9.4.18.v20190429]
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:278) ~[jetty-servlet-9.4.18.v20190429.jar:9.4.18.v20190429]
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545) [jetty-webapp-9.4.18.v20190429.jar:9.4.18.v20190429]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.4.18.v20190429.jar:9.4.18.v20190429]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167) [jetty-util-9.4.18.v20190429.jar:9.4.18.v20190429]
        at org.eclipse.jetty.server.Server.start(Server.java:418) [jetty-server-9.4.18.v20190429.jar:9.4.18.v20190429]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110) [jetty-util-9.4.18.v20190429.jar:9.4.18.v20190429]
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113) [jetty-server-9.4.18.v20190429.jar:9.4.18.v20190429]
        at org.eclipse.jetty.server.Server.doStart(Server.java:382) [jetty-server-9.4.18.v20190429.jar:9.4.18.v20190429]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.4.18.v20190429.jar:9.4.18.v20190429]
        at de.rwh.utils.jetty.JettyServer.start(JettyServer.java:334) [jetty-utils-0.4.0.jar:0.4.0]
        at org.highmed.dsf.fhir.FhirServer.startServer(FhirServer.java:78) [classes/:?]
        at org.highmed.dsf.fhir.FhirServer.startHttpsServer(FhirServer.java:46) [classes/:?]
        at org.highmed.dsf.fhir.FhirJettyServerHttps.main(FhirJettyServerHttps.java:7) [classes/:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282) [exec-maven-plugin-1.6.0.jar:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
INFO    org.highmed.dsf.fhir.FhirJettyServerHttps.main() - HouseKeeper.stopScavenging(167) | node0 Stopped scavenging
java.lang.NullPointerException    
        at org.highmed.dsf.fhir.authentication.AuthenticationFilter.init(AuthenticationFilter.java:37)
        at org.eclipse.jetty.servlet.FilterHolder.initialize(FilterHolder.java:136)
        at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$0(ServletHandler.java:750)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
        at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:744)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:369)
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1497)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1459)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:852)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:278)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167)
        at org.eclipse.jetty.server.Server.start(Server.java:418)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
        at org.eclipse.jetty.server.Server.doStart(Server.java:382)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at de.rwh.utils.jetty.JettyServer.start(JettyServer.java:334)
        at org.highmed.dsf.fhir.FhirServer.startServer(FhirServer.java:78)
        at org.highmed.dsf.fhir.FhirServer.startHttpsServer(FhirServer.java:46)
        at org.highmed.dsf.fhir.FhirJettyServerHttps.main(FhirJettyServerHttps.java:7)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
        at java.base/java.lang.Thread.run(Thread.java:834)
INFO    org.highmed.dsf.fhir.FhirJettyServerHttps.main() - ContextHandler.doStop(1045) | Stopped o.e.j.w.WebAppContext@45686e58{/fhir,null,UNAVAILABLE}
```
Any Idea what I'm doing wrong?

**Comment by hhund** [comment]
Not sure. So far I've never tried starting the servers with the exec maven plugin. Usually the AuthenticationFilter is initialized after the Spring app context and Jersey are started. Maybe the auto-detection of the Spring WebApplicationInitializer -> FhirSpringApplication, and the Jersey ResourceConfig -> FhirJerseyApplication does not work, when starting this way.

**Comment by hhund** [comment]
Your log entries
```
INFO    org.highmed.dsf.fhir.FhirJettyServerHttps.main() - JettyServer.<init>(299) | Web inf classes: dirs []
INFO    org.highmed.dsf.fhir.FhirJettyServerHttps.main() - JettyServer.<init>(300) | Web inf classes: jars []
```
seem to suggest that there is some thing wrong with the class-path config.

When I start the FHIR server from eclipse it reads:
```
INFO	main - JettyServer.<init>(299) | Web inf classes: dirs [file:///**folder-on-my-machine**/highmed-dsf/dsf-fhir/dsf-fhir-server-jetty/target/classes/, file:///**folder-on-my-machine**/highmed-dsf/dsf-fhir/dsf-fhir-server/target/classes/]
INFO	main - JettyServer.<init>(300) | Web inf classes: jars []
```
and via docker the output is:
```
INFO main - JettyServer.<init>(299) | Web inf classes: dirs []
INFO main - JettyServer.<init>(300) | Web inf classes: jars [file:///opt/fhir/lib/dsf-fhir-server-0.1.0-SNAPSHOT.jar]
```

**Comment by hhund** [comment]
If you want to start the FHIR server from the command-line on Windows, you could try in the ...\highmed-dsf\dsf-fhir\dsf-fhir-server-jetty folder:
`java -cp docker\lib\*.jar;target\classes org.highmed.dsf.fhir.FhirJettyServerHttps`

**Comment by hhund** [comment]
Also working on my machine:
```
mvn exec:exec -Dexec.executable="java" -Dexec.args="-classpath %classpath org.highmed.dsf.fhir.FhirJettyServerHttps"
```
(again from the ...\highmed-dsf\dsf-fhir\dsf-fhir-server-jetty folder)

**Comment by FloSeidel** [comment]
Sorry for the delayed response! 
To solve the problem I downloaded eclipse and started the Apps from the UI.

The java command:
```java -cp docker\lib\*.jar;target\classes org.highmed.dsf.fhir.FhirJettyServerHttps``` did not work for me, because no class definition could be found (java.lang.NoClassDefFoundError:). The addition of "../dsf-fhir-server/target/classes" didn't help either.


PS: I can reproduce the behaviour with the mvn command...

**Comment by hhund** [comment]
Looks like I did not copy the correct command. _'*.jar'_ is wrong. Please try again with:
```
java -cp  docker/lib/*;target/classes org.highmed.dsf.fhir.FhirJettyServerHttps
```
If the error persists please add the stack-trace of the NoClassDefFoundError or at least the mentioned full name of the class that could not be found.

**Comment by FloSeidel** [comment]
I'm feeling just a little stupid ;D Works like a charm :)
