### ISSUE TITLE
DSF-DB is locked after version update

### ISSUE THREAD

**Issue by bauerjs1** [highmed/highmed-dsf#292]
After upgrading the DB container `postgres:13.4-alpine -> postgres:13.5-alpine`, the DSF-FHIR cannot perform its DB migration step, because tables seem to be still locked. Could it be that on DSF container termination, it misses to unlock some tables?

The logs tell me this:
```
Executing DSF FHIR with
openjdk 11.0.12 2021-07-20
OpenJDK Runtime Environment 18.9 (build 11.0.12+7)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.12+7, mixed mode, sharing)
INFO main - DbMigrator.migrate(52) | Executing DB migration ...
ERROR main - DbMigrator.migrate(65) | Error while running liquibase: Could not acquire change log lock.  Currently locked by 575da2e2e672 (192.168.208.3) since 10/10/21, 6:05 AM
Exception in thread "main" java.lang.RuntimeException: liquibase.exception.LockException: Could not acquire change log lock.  Currently locked by 575da2e2e672 (192.168.208.3) since 10/10/21, 6:05 AM
	at org.highmed.dsf.tools.db.DbMigrator.migrate(DbMigrator.java:66)
	at org.highmed.dsf.tools.db.DbMigrator.retryOnConnectException(DbMigrator.java:87)
	at org.highmed.dsf.fhir.FhirServer.startServer(FhirServer.java:74)
	at org.highmed.dsf.fhir.FhirServer.startHttpServer(FhirServer.java:54)
	at org.highmed.dsf.fhir.FhirJettyServer.main(FhirJettyServer.java:9)
Caused by: liquibase.exception.LockException: Could not acquire change log lock.  Currently locked by 575da2e2e672 (192.168.208.3) since 10/10/21, 6:05 AM
	at liquibase.lockservice.StandardLockService.waitForLock(StandardLockService.java:234)
	at liquibase.Liquibase.lambda$update$1(Liquibase.java:214)
	at liquibase.Scope.lambda$child$0(Scope.java:177)
	at liquibase.Scope.child(Scope.java:186)
	at liquibase.Scope.child(Scope.java:176)
	at liquibase.Scope.child(Scope.java:155)
	at liquibase.Liquibase.runInScope(Liquibase.java:2404)
	at liquibase.Liquibase.update(Liquibase.java:211)
	at liquibase.Liquibase.update(Liquibase.java:197)
	at liquibase.Liquibase.update(Liquibase.java:193)
	at org.highmed.dsf.tools.db.DbMigrator.migrate(DbMigrator.java:53)
	... 4 more
java exited with code 1
```

Given by the time this lock has been acquired, I am pretty sure there was no manual intervention by myself. The funny part is, that this lock seems to have existed already during DSF update to v0.5.3 and has not been a problem at that time.

**Comment by hhund** [comment]
During the startup of the DSF-FHIR and DSF-BPE containers, a data base migration is performed using Liquibase. Liquibase creates a "lock" by modifying an entry in the `databasechangeloglock` table. The lock is removed, when Liquibase is finished with the migration tasks.

If the lock is not removed, this typically means that the container was forcefully stopped while performing the database migration. Running the following SQL on the database will release the lock:
```
UPDATE databasechangeloglock SET locked = FALSE, lockgranted = NULL, lockedby = NULL WHERE id = 1;
```

**Comment by bauerjs1** [comment]
Alright. Since this lock is very old, I cannot really determine its cause anymore.
Nevertheless, thanks for the solution, the DSF container is working again!
