### ISSUE TITLE
Cannot get StructureDefinitions as HTML if the current ping process is deployed

### ISSUE THREAD

**Issue by schwzr** [highmed/highmed-dsf#363]
In DSF Version 0.7.0 you receive a HTTP 500 status code when you try to get the StructureDefinitions (e.g. `https://DSF-FHIR-FQDN/fhir/StructureDefinition?_count=200`).

This does NOT affect requests where the Content-Types `application/fhir+json` or `application/fhir+xml` are accepted.

When you remove the ping process in your BPE installation the StructureDefinitions will be returned. 

According to the logs this seems to be a regex issue [here](https://github.com/highmed/highmed-dsf/blob/main/dsf-fhir/dsf-fhir-rest-adapter/src/main/java/org/highmed/dsf/fhir/adapter/HtmlFhirAdapter.java#L284):

```
fhir-app-1    | Caused by: java.lang.IllegalArgumentException: Illegal group reference
fhir-app-1    | 	at java.util.regex.Matcher.appendExpandedReplacement(Unknown Source) ~[?:?]
fhir-app-1    | 	at java.util.regex.Matcher.appendReplacement(Unknown Source) ~[?:?]
fhir-app-1    | 	at java.util.regex.Matcher.replaceAll(Unknown Source) ~[?:?]
fhir-app-1    | 	at org.highmed.dsf.fhir.adapter.HtmlFhirAdapter.simplifyXml(HtmlFhirAdapter.java:284) ~[dsf-fhir-rest-adapter-0.7.0.jar:0.7.0]
fhir-app-1    | 	at org.highmed.dsf.fhir.adapter.HtmlFhirAdapter.writeXml(HtmlFhirAdapter.java:257) ~[dsf-fhir-rest-adapter-0.7.0.jar:0.7.0]
fhir-app-1    | 	at org.highmed.dsf.fhir.adapter.HtmlFhirAdapter.writeTo(HtmlFhirAdapter.java:188) ~[dsf-fhir-rest-adapter-0.7.0.jar:0.7.0]
fhir-app-1    | 	at org.highmed.dsf.fhir.adapter.HtmlFhirAdapter.writeTo(HtmlFhirAdapter.java:33) ~[dsf-fhir-rest-adapter-0.7.0.jar:0.7.0]

```

I traced it down to the following string [here](https://github.com/highmed/highmed-processes/blob/v0.6.0/dsf-bpe-process-ping/src/main/resources/fhir/StructureDefinition/highmed-task-start-ping-autostart.xml#L146), but at the first glance I can't see any obvious reason why it fails:

```xml
<expression value="matches('^P(?:([0-9]+)Y)?(?:([0-9]+)M)?(?:([0-9]+)D)?(T(?:([0-9]+)H)?(?:([0-9]+)M)?(?:([0-9]+)(?:[.,]([0-9]{0,9}))?S)?)?$')"></expression>
```

You can find a minimal example to reproduce the issue here:

```java
import java.io.IOException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class Main {
    private static final Pattern CLOSABLE_XML_TAGS = Pattern
            .compile("(m?)[\\t ]*<[a-zA-Z0-9]+( value=\".*\"){0,1}(></[a-zA-Z0-9]+>)");
    public static void main(String[] args) throws IOException {
        String s = "<expression value=\"matches('^P(?:([0-9]+)Y)?(?:([0-9]+)M)?(?:([0-9]+)D)?(T(?:([0-9]+)H)?(?:([0-9]+)M)?(?:([0-9]+)(?:[.,]([0-9]{0,9}))?S)?)?$')\"></expression>\n";
        Matcher matcher = CLOSABLE_XML_TAGS.matcher(s);
        String s2 = matcher.replaceAll(r -> {
            System.out.println(r.group());
            System.out.println(r.group(3));
            return r.group().replace(r.group(3), "/>");
        });
    }
}
```

**Comment by hhund** [comment]
The problem seems to be a result of the way the `replaceAll` method works internally with a replacer-function. It seems that the input String for the matcher may not contain unescaped `$` characters.  

Adding a `s = s.replace("$", "\\$");` to the minimal example above fixes the `java.lang.IllegalArgumentException: Illegal group reference` and gives the expected result:

```xml
<expression value="matches('^P(?:([0-9]+)Y)?(?:([0-9]+)M)?(?:([0-9]+)D)?(T(?:([0-9]+)H)?(?:([0-9]+)M)?(?:([0-9]+)(?:[.,]([0-9]{0,9}))?S)?)?$')"/>
```

```java
import java.io.IOException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class Main {
    private static final Pattern CLOSABLE_XML_TAGS = Pattern
            .compile("(m?)[\\t ]*<[a-zA-Z0-9]+( value=\".*\"){0,1}(></[a-zA-Z0-9]+>)");
    public static void main(String[] args) throws IOException {
        String s = "<expression value=\"matches('^P(?:([0-9]+)Y)?(?:([0-9]+)M)?(?:([0-9]+)D)?(T(?:([0-9]+)H)?(?:([0-9]+)M)?(?:([0-9]+)(?:[.,]([0-9]{0,9}))?S)?)?$')\"></expression>\n";
        s = s.replace("$", "\\$"); //<- fix for Illegal group reference
        Matcher matcher = CLOSABLE_XML_TAGS.matcher(s);
        String s2 = matcher.replaceAll(r -> {
            System.out.println(r.group());
            System.out.println(r.group(3));
            return r.group().replace(r.group(3), "/>");
        });
        System.out.println(s2);
    }
}
```

**Comment by hhund** [comment]
Alternatively we could replace the regex-code with a `javax.xml.transform.Transformer`:

```java
import java.io.StringReader;
import java.io.StringWriter;

import javax.xml.transform.OutputKeys;
import javax.xml.transform.Source;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.stream.StreamResult;
import javax.xml.transform.stream.StreamSource;

public class XmlTransformerTest
{
	public static void main(String[] args) throws Exception
	{
		String s = "<expression value=\"matches('^P(?:([0-9]+)Y)?(?:([0-9]+)M)?(?:([0-9]+)D)?(T(?:([0-9]+)H)?(?:([0-9]+)M)?(?:([0-9]+)(?:[.,]([0-9]{0,9}))?S)?)?$')\"></expression>";
		
		Transformer transformer = TransformerFactory.newInstance().newTransformer();
		transformer.setOutputProperty(OutputKeys.METHOD, "xml");
		transformer.setOutputProperty(OutputKeys.OMIT_XML_DECLARATION, "yes");
		transformer.setOutputProperty(OutputKeys.INDENT, "yes");
		transformer.setOutputProperty("{http://xml.apache.org/xalan}indent-amount", "3");
		StringWriter writer = new StringWriter();
		transformer.transform(new StreamSource(new StringReader(s)), new StreamResult(writer));
		String s2 = writer.toString();
		System.out.println(s2);
	}
}
```
_Caution: The `Transformer` class is not thread-save._

**Comment by hhund** [comment]
There is another related issue, with the HTML output generated for `OrganizationAffiliation` pages:
```xml
<participatingOrganization>
    <reference value="Organization/34575bc7-28b4-4028-bf7a-75bb5777851a">
    <type value="Organization"/>
</participatingOrganization>
```

The `reference` tag is missing a `/`. Thanks to G. Fette for reporting the issue.
